export default {
  SCHEMA: 'SCHEMA',
  TABLE: 'TABLE',
  COLUMN: 'COLUMN',
  CONSTRAINT: 'CONSTRAINT',
  INDEX: 'INDEX',
  POLICY: 'POLICY',
  VIEW: 'VIEW',
  MATERIALIZED_VIEW: 'MATERIALIZED VIEW',
  FUNCTION: 'FUNCTION',
  AGGREGATE: 'AGGREGATE',
  SEQUENCE: 'SEQUENCE',
  PROCEDURE: 'PROCEDURE',
} as const;
